// Built-in game catalog. The spec calls for pulling titles from IGDB via an
// AJAX search, but IGDB needs OAuth credentials and a live network — neither of
// which suits a self-contained, no-build project. So we ship a curated local
// catalog instead and search it instantly in memory. Swapping in the real IGDB
// API later means only replacing `searchGames()` in script.js.
window.GAME_CATALOG = [
  { title: 'The Legend of Zelda: Tears of the Kingdom', year: 2023, genre: 'Adventure' },
  { title: 'Elden Ring', year: 2022, genre: 'RPG' },
  { title: 'Baldur’s Gate 3', year: 2023, genre: 'RPG' },
  { title: 'Hades', year: 2020, genre: 'Roguelike' },
  { title: 'Hades II', year: 2024, genre: 'Roguelike' },
  { title: 'Stardew Valley', year: 2016, genre: 'Simulation' },
  { title: 'Hollow Knight', year: 2017, genre: 'Metroidvania' },
  { title: 'Celeste', year: 2018, genre: 'Platformer' },
  { title: 'Portal 2', year: 2011, genre: 'Puzzle' },
  { title: 'Half-Life: Alyx', year: 2020, genre: 'Shooter' },
  { title: 'Counter-Strike 2', year: 2023, genre: 'Shooter' },
  { title: 'Valorant', year: 2020, genre: 'Shooter' },
  { title: 'Overwatch 2', year: 2022, genre: 'Shooter' },
  { title: 'Apex Legends', year: 2019, genre: 'Battle Royale' },
  { title: 'Fortnite', year: 2017, genre: 'Battle Royale' },
  { title: 'Minecraft', year: 2011, genre: 'Sandbox' },
  { title: 'Terraria', year: 2011, genre: 'Sandbox' },
  { title: 'Cyberpunk 2077', year: 2020, genre: 'RPG' },
  { title: 'The Witcher 3: Wild Hunt', year: 2015, genre: 'RPG' },
  { title: 'Red Dead Redemption 2', year: 2018, genre: 'Adventure' },
  { title: 'Grand Theft Auto V', year: 2013, genre: 'Adventure' },
  { title: 'God of War Ragnarök', year: 2022, genre: 'Adventure' },
  { title: 'Ghost of Tsushima', year: 2020, genre: 'Adventure' },
  { title: 'Marvel’s Spider-Man 2', year: 2023, genre: 'Adventure' },
  { title: 'Super Mario Odyssey', year: 2017, genre: 'Platformer' },
  { title: 'Super Smash Bros. Ultimate', year: 2018, genre: 'Fighting' },
  { title: 'Mario Kart 8 Deluxe', year: 2017, genre: 'Racing' },
  { title: 'Animal Crossing: New Horizons', year: 2020, genre: 'Simulation' },
  { title: 'Splatoon 3', year: 2022, genre: 'Shooter' },
  { title: 'Pokémon Scarlet & Violet', year: 2022, genre: 'RPG' },
  { title: 'Final Fantasy XVI', year: 2023, genre: 'RPG' },
  { title: 'Final Fantasy VII Rebirth', year: 2024, genre: 'RPG' },
  { title: 'Persona 5 Royal', year: 2019, genre: 'RPG' },
  { title: 'Monster Hunter: World', year: 2018, genre: 'Action RPG' },
  { title: 'Diablo IV', year: 2023, genre: 'Action RPG' },
  { title: 'Destiny 2', year: 2017, genre: 'Shooter' },
  { title: 'Sea of Thieves', year: 2018, genre: 'Adventure' },
  { title: 'It Takes Two', year: 2021, genre: 'Co-op' },
  { title: 'Overcooked! 2', year: 2018, genre: 'Co-op' },
  { title: 'Fall Guys', year: 2020, genre: 'Party' },
  { title: 'Among Us', year: 2018, genre: 'Party' },
  { title: 'Jackbox Party Pack', year: 2014, genre: 'Party' },
  { title: 'Rocket League', year: 2015, genre: 'Sports' },
  { title: 'FIFA 24 (EA Sports FC 24)', year: 2023, genre: 'Sports' },
  { title: 'Forza Horizon 5', year: 2021, genre: 'Racing' },
  { title: 'Gran Turismo 7', year: 2022, genre: 'Racing' },
  { title: 'Cuphead', year: 2017, genre: 'Platformer' },
  { title: 'Ori and the Will of the Wisps', year: 2020, genre: 'Metroidvania' },
  { title: 'Dead Cells', year: 2018, genre: 'Roguelike' },
  { title: 'Slay the Spire', year: 2019, genre: 'Roguelike' },
  { title: 'Balatro', year: 2024, genre: 'Roguelike' },
  { title: 'Vampire Survivors', year: 2022, genre: 'Roguelike' },
  { title: 'Disco Elysium', year: 2019, genre: 'RPG' },
  { title: 'Undertale', year: 2015, genre: 'RPG' },
  { title: 'Palworld', year: 2024, genre: 'Survival' },
  { title: 'Valheim', year: 2021, genre: 'Survival' },
  { title: 'Rust', year: 2018, genre: 'Survival' },
  { title: 'Don’t Starve Together', year: 2016, genre: 'Survival' },
  { title: 'Deep Rock Galactic', year: 2020, genre: 'Co-op' },
  { title: 'Helldivers 2', year: 2024, genre: 'Shooter' }
];
