// Recipe data — "recipes are nothing more than culinary algorithms."
// Each recipe is a plain object. Amounts live with their ingredient so the
// card can render them as a single line. `emoji` stands in for a dish photo.
const RECIPES = [
  {
    id: "pancakes",
    title: "Fluffy Buttermilk Pancakes",
    emoji: "🥞",
    mealType: "breakfast",
    servings: 4,
    difficulty: "beginner",
    minutes: 25,
    ingredients: [
      { amount: "2 cups", item: "all-purpose flour" },
      { amount: "2 tbsp", item: "sugar" },
      { amount: "1 tbsp", item: "baking powder" },
      { amount: "½ tsp", item: "salt" },
      { amount: "2 cups", item: "buttermilk" },
      { amount: "2", item: "eggs" },
      { amount: "3 tbsp", item: "melted butter" },
    ],
    steps: [
      "Whisk the flour, sugar, baking powder and salt in a large bowl.",
      "In another bowl beat the buttermilk, eggs and melted butter together.",
      "Pour the wet into the dry and stir until just combined — lumps are fine.",
      "Ladle ¼-cup pools onto a buttered skillet over medium heat.",
      "Flip when bubbles form and the edges set; cook until golden.",
      "Serve warm with butter and maple syrup.",
    ],
  },
  {
    id: "omelette",
    title: "Three-Egg Cheese Omelette",
    emoji: "🍳",
    mealType: "breakfast",
    servings: 1,
    difficulty: "intermediate",
    minutes: 10,
    ingredients: [
      { amount: "3", item: "eggs" },
      { amount: "2 tbsp", item: "milk" },
      { amount: "½ cup", item: "grated cheddar" },
      { amount: "1 tbsp", item: "butter" },
      { amount: "to taste", item: "salt and pepper" },
    ],
    steps: [
      "Beat the eggs with the milk, salt and pepper until uniform.",
      "Melt the butter in a non-stick pan over medium-low heat.",
      "Pour in the eggs and let them set at the edges, tilting to fill gaps.",
      "Scatter the cheese over one half when the top is just barely wet.",
      "Fold the empty half over the cheese and slide onto a plate.",
    ],
  },
  {
    id: "caprese",
    title: "Caprese Salad",
    emoji: "🥗",
    mealType: "lunch",
    servings: 2,
    difficulty: "beginner",
    minutes: 10,
    ingredients: [
      { amount: "3", item: "ripe tomatoes" },
      { amount: "8 oz", item: "fresh mozzarella" },
      { amount: "1 bunch", item: "fresh basil" },
      { amount: "3 tbsp", item: "olive oil" },
      { amount: "1 tbsp", item: "balsamic glaze" },
      { amount: "to taste", item: "flaky salt" },
    ],
    steps: [
      "Slice the tomatoes and mozzarella into rounds about ¼-inch thick.",
      "Alternate tomato and mozzarella slices on a platter, tucking basil between.",
      "Drizzle with olive oil and balsamic glaze.",
      "Finish with a pinch of flaky salt and serve right away.",
    ],
  },
  {
    id: "grilled-cheese",
    title: "Classic Grilled Cheese",
    emoji: "🧀",
    mealType: "lunch",
    servings: 1,
    difficulty: "beginner",
    minutes: 8,
    ingredients: [
      { amount: "2 slices", item: "sourdough bread" },
      { amount: "2 slices", item: "cheddar" },
      { amount: "1 slice", item: "gruyère" },
      { amount: "2 tbsp", item: "softened butter" },
    ],
    steps: [
      "Butter the outside face of each slice of bread.",
      "Layer the cheeses between the slices, buttered sides facing out.",
      "Cook in a skillet over medium-low heat until golden, about 3 minutes.",
      "Flip and cook the other side until the cheese is fully melted.",
      "Rest one minute, then cut on the diagonal.",
    ],
  },
  {
    id: "spaghetti",
    title: "Spaghetti Aglio e Olio",
    emoji: "🍝",
    mealType: "supper",
    servings: 2,
    difficulty: "intermediate",
    minutes: 20,
    ingredients: [
      { amount: "8 oz", item: "spaghetti" },
      { amount: "6 cloves", item: "garlic, thinly sliced" },
      { amount: "⅓ cup", item: "olive oil" },
      { amount: "½ tsp", item: "red pepper flakes" },
      { amount: "¼ cup", item: "chopped parsley" },
      { amount: "to taste", item: "salt" },
    ],
    steps: [
      "Boil the spaghetti in well-salted water until al dente; reserve a cup of pasta water.",
      "Gently warm the olive oil and garlic in a wide pan until the garlic is pale gold.",
      "Add the red pepper flakes and a splash of pasta water to make a light sauce.",
      "Toss in the drained pasta and stir to coat, loosening with pasta water as needed.",
      "Off the heat, fold in the parsley and serve immediately.",
    ],
  },
  {
    id: "chili",
    title: "Weeknight Beef Chili",
    emoji: "🌶️",
    mealType: "supper",
    servings: 6,
    difficulty: "intermediate",
    minutes: 45,
    ingredients: [
      { amount: "1 lb", item: "ground beef" },
      { amount: "1", item: "onion, diced" },
      { amount: "2 cloves", item: "garlic, minced" },
      { amount: "2 tbsp", item: "chili powder" },
      { amount: "1 can", item: "diced tomatoes" },
      { amount: "1 can", item: "kidney beans, drained" },
      { amount: "1 cup", item: "beef broth" },
    ],
    steps: [
      "Brown the beef in a heavy pot over medium-high heat, breaking it up.",
      "Add the onion and garlic and cook until softened, about 5 minutes.",
      "Stir in the chili powder and cook for one minute until fragrant.",
      "Add the tomatoes, beans and broth; bring to a simmer.",
      "Lower the heat and simmer uncovered for 30 minutes, stirring now and then.",
      "Season to taste and serve with your favourite toppings.",
    ],
  },
  {
    id: "guacamole",
    title: "Fresh Guacamole",
    emoji: "🥑",
    mealType: "snack",
    servings: 4,
    difficulty: "beginner",
    minutes: 15,
    ingredients: [
      { amount: "3", item: "ripe avocados" },
      { amount: "1", item: "lime, juiced" },
      { amount: "½", item: "red onion, finely diced" },
      { amount: "1", item: "small tomato, diced" },
      { amount: "2 tbsp", item: "chopped cilantro" },
      { amount: "to taste", item: "salt" },
    ],
    steps: [
      "Halve the avocados, scoop the flesh into a bowl and mash to your liking.",
      "Stir in the lime juice right away to keep the colour bright.",
      "Fold in the onion, tomato and cilantro.",
      "Season with salt and serve with chips.",
    ],
  },
  {
    id: "energy-balls",
    title: "No-Bake Energy Balls",
    emoji: "🍪",
    mealType: "snack",
    servings: 12,
    difficulty: "beginner",
    minutes: 20,
    ingredients: [
      { amount: "1 cup", item: "rolled oats" },
      { amount: "½ cup", item: "peanut butter" },
      { amount: "⅓ cup", item: "honey" },
      { amount: "½ cup", item: "mini chocolate chips" },
      { amount: "1 tsp", item: "vanilla extract" },
    ],
    steps: [
      "Mix all the ingredients in a bowl until evenly combined.",
      "Chill the mixture for 15 minutes so it firms up enough to roll.",
      "Scoop and roll into 1-inch balls.",
      "Store in the fridge in an airtight container.",
    ],
  },
];
