'use strict';

/*
 * Podcast Directory — the real scraper.
 *
 * This is the mechanism the app-ideas spec describes: use Puppeteer to open
 * each podcast's Podbean page, read the episode links out of the DOM with
 * querySelectorAll, and merge everything into one date-sorted list.
 *
 * The browser app (index.html) can't do this itself — a page can't run a
 * headless browser and can't fetch podbean.com cross-origin — so it renders a
 * bundled snapshot (episodes.js) instead. Run this script to regenerate that
 * snapshot from live pages:
 *
 *   npm install puppeteer
 *   node scrape.js            # prints combined, date-sorted JSON
 *   node scrape.js --write    # also rewrites episodes.js for the browser app
 *
 * Podbean markup changes over time; treat the selectors below as a starting
 * point and adjust if a run comes back empty.
 */

const fs = require('fs');
const path = require('path');

const PODCASTS = [
  { name: 'JavaScript Jabber', url: 'https://javascriptjabber.podbean.com/' },
  { name: 'Techpoint Charlie', url: 'https://techpointcharlie.podbean.com/' },
];

async function scrapePodcast(browser, podcast) {
  const page = await browser.newPage();
  await page.goto(podcast.url, { waitUntil: 'networkidle2', timeout: 60000 });

  // Pull episode title, link and date straight out of the rendered DOM.
  const episodes = await page.evaluate(() => {
    const out = [];
    // Podbean lists each episode inside an element carrying its title and a
    // permalink. These selectors cover the common Podbean layouts.
    const items = document.querySelectorAll(
      '.pod-item, .episode-item, article, li.episode'
    );
    items.forEach((item) => {
      const link = item.querySelector('a[href*="/podbean.com/"], a.pod-title, h3 a, a[href*="podbean"]');
      const timeEl = item.querySelector('time, .pubdate, .date, [datetime]');
      if (!link) return;
      const title = (link.textContent || '').trim();
      const url = link.href;
      const date =
        (timeEl && (timeEl.getAttribute('datetime') || timeEl.textContent)) || '';
      if (title && url) out.push({ title, url, date: date.trim() });
    });
    return out;
  });

  await page.close();
  return episodes.map((ep) => ({ podcast: podcast.name, ...ep, date: normalizeDate(ep.date) }));
}

// Best-effort conversion of whatever Podbean renders into ISO yyyy-mm-dd.
function normalizeDate(raw) {
  if (!raw) return '';
  const d = new Date(raw);
  if (Number.isNaN(d.getTime())) return raw;
  return d.toISOString().slice(0, 10);
}

function toEpisodesModule(episodes) {
  const rows = episodes
    .map(
      (e) =>
        `  { podcast: ${JSON.stringify(e.podcast)}, title: ${JSON.stringify(
          e.title
        )}, date: ${JSON.stringify(e.date)}, url: ${JSON.stringify(e.url)} },`
    )
    .join('\n');
  return `// Auto-generated by scrape.js — do not edit by hand.\nwindow.PODCAST_EPISODES = [\n${rows}\n];\n`;
}

async function main() {
  let puppeteer;
  try {
    puppeteer = require('puppeteer');
  } catch (err) {
    console.error('Puppeteer is not installed. Run: npm install puppeteer');
    process.exit(1);
  }

  const browser = await puppeteer.launch({ headless: 'new' });
  try {
    const perPodcast = await Promise.all(
      PODCASTS.map((p) => scrapePodcast(browser, p))
    );
    const all = perPodcast
      .flat()
      // Combined and sorted newest first.
      .sort((a, b) => String(b.date).localeCompare(String(a.date)));

    console.log(JSON.stringify(all, null, 2));

    if (process.argv.includes('--write')) {
      const dest = path.join(__dirname, 'episodes.js');
      fs.writeFileSync(dest, toEpisodesModule(all));
      console.error(`Wrote ${all.length} episodes to ${dest}`);
    }
  } finally {
    await browser.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
